const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGIN_LOADING = "LOGIN_LOADING";
const GET_DATA = "GET_DATA";

export { LOGIN_FAIL, LOGIN_LOADING, LOGIN_SUCCESS, GET_DATA };
